variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------

.win_base:
  stage: build
  tags:
    - sdk
    - win10

.c_base:
  stage: build
  tags:
    - sdk
    - bionic

# -----------------------------------------------------------------------------
# Builds
# -----------------------------------------------------------------------------

build::Laboratory:
  extends: .win_base
  script:
    - cd Laboratory
    - ./BuildCompilers.bat

build::LMNT:
  extends: .c_base
  script:
    - cd LMNT
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --config RelWithDebInfo

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------

test:
  extends: .win_base
  stage: test
  script:
    - cd Laboratory
    - ./RunTests.bat
