name: LMNT

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - run: cd LMNT
           mkdir build
           cd build
           cmake ..
           cmake --build . --config RelWithDebInfo
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       # Artifact name
       name: LMNT
       # Directory containing files to upload
       path: LMNT/build
